### ISSUE TITLE
Managing composer package

### ISSUE THREAD

**Issue by jmikola** [Exercise/HTMLPurifierBundle#13]
@cystbear: Would you like to assume ownership of the [exercise/htmlpurifier-bundle](https://packagist.org/packages/exercise/htmlpurifier-bundle) package on Packagist? The repository is not currently setup with a commit hook, so that would at least need to be setup. Beyond that, the bundle could probably benefit from Travis CI integration, listing the appropriate Symfony2 version in its `composer.json`, and receiving a proper git tag (there is only a `master` branch so that could easily start at `v1.0.0`).

Let me know if you're interested and I'll swap our names on the maintainers list. Thanks.

**Comment by Nek-** [comment]
Why you didn't release a 1.0.0 version ?

**Comment by tgabi333** [comment]
+1 for 1.0.0 release :)

**Comment by mychalvlcek** [comment]
how about publish new package version as it supports SF3?

**Comment by spolischook** [comment]
@mychalvlcek https://github.com/Exercise/HTMLPurifierBundle/releases/tag/v0.2.3

**Comment by HeahDude** [comment]
Can we close here?

**Comment by cystbear** [comment]
@HeahDude I think yes

**Comment by spolischook** [comment]
Close this very old issue
