### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by AlexanderMatveev** [Exercise/HTMLPurifierBundle#45]

**Comment by Richard87** [comment]
The prelease works nicely! No deprecations, and everything works without chaning anything :)

I'm using commit #308b47f2f11bbc17c102c3eba92272949957c5c4

**Comment by spolischook** [comment]
Yep, it already in master https://github.com/Exercise/HTMLPurifierBundle/pull/47. Thanks for your contributions
