### ISSUE TITLE
Cache directory is not being created by the bundle, v2.0

### ISSUE THREAD

**Issue by alister** [Exercise/HTMLPurifierBundle#54]
The line `<tag name="kernel.cache_warmer" />` has been removed from the file `./Resources/config/html_purifier.xml`, and so the cache warmer is not being run on the framework startup.

Further, when the cache is being built, there are issues with `key="$paths"` unless it is removed OR a `key="$htmlPurifier"` is added on the next line.

Both of these for the block `<service id="exercise_html_purifier.cache_warmer.serializer"  ...`, work.

    <argument>%exercise_html_purifier.cache_warmer.serializer.paths%</argument>
    <argument type="service" id="HTMLPurifier" />
    <tag name="kernel.cache_warmer" />

OR

    <argument key="$paths">%exercise_html_purifier.cache_warmer.serializer.paths%</argument>
    <argument key="$htmlPurifier" type="service" id="HTMLPurifier" />
    <tag name="kernel.cache_warmer" />

**Comment by asentner** [comment]
Thanks for the fix! Looks like I'll be using a forked version for now until this gets merged in.

**Comment by spolischook** [comment]
np, just remember that test that you write (should write) with your PR, can increase the time for review and durability of your changes.

**Comment by jrjohnson** [comment]
Thanks, the fix in `V2.0.0-BETA2` works.  Just a note to anyone else tracking this ticket - I had to upgrade from `2.0.0` to `2.0.0-BEAT2` manually since composer didn't see the `BETA` tag as a stable update from `2.0.0` and a regular `composer update` wont cut it.

**Comment by spolischook** [comment]
@jrjohnson thanks for the note. I've update the version https://github.com/Exercise/HTMLPurifierBundle/releases/tag/V2.0.1

**Comment by jrjohnson** [comment]
@spolischook thanks, but it still doesn't show up as the latest on https://packagist.org/packages/exercise/htmlpurifier-bundle
