### ISSUE TITLE
The option "purify_html_profile" with value null is expected to be of type "string", but is of type "NULL".

### ISSUE THREAD

**Issue by SvetlinStaev** [Exercise/HTMLPurifierBundle#57]
I have upgraded the bundle to the latest version and I observe the following error:

`The option "purify_html_profile" with value null is expected to be of type "string", but is of type "NULL".`

This error occurs on fields which are modify any of the form options through a form event subscriber like:

```
        $parent  = $field->getParent();
        $options = $field->getConfig()->getOptions();
        $name    = $field->getName();

        $parent->remove($name);
        $parent->add($name, $type, \array_merge($options, ['disabled' => $disabled]));
```

In this code I disable the field based on some condition, the field does not have `purify_html` yet the error occurs. I noticed the following in the form extension:

```
            ->setAllowedTypes('purify_html_profile', 'string')
            ->setNormalizer('purify_html_profile', function (Options $options, $profile) {
                if (!$options['purify_html']) {
                    return null;
                }
```

I believe this is causing the issue since it requires the profile to be a string, yet it is normalized to null.

**Comment by spolischook** [comment]
Hi, @SvetlinStaev! 
Can you make fully working example of en error, with purify configuration and form code to make it reproducible

**Comment by SvetlinStaev** [comment]
HI,

I will try to make a repro about it but I see it has already been fixed in PR #53

**Comment by spolischook** [comment]
Try V2.0.2, it should be fixed

**Comment by SvetlinStaev** [comment]
It fails to pull 2.0.2 based on `"exercise/htmlpurifier-bundle": "^2.0",` constraint in my `composer.json`. But I tried using the code from that tag and it works fine.
