### ISSUE TITLE
The purifying listener does not properly trim the field if there are only whitespaces.

### ISSUE THREAD

**Issue by stof** [Exercise/HTMLPurifierBundle#58]
The form type extension disables the `trim` option when the `purify_html` option is enabled, saying that the listener already trims.
But the trimmed value is not always written back to the event. If trimming makes it empty, the value is not replaced in the event.

**Comment by spolischook** [comment]
@stof I'm not actively used this component, so It would be great to have test and fix - I'll merge it asap.

**Comment by HeahDude** [comment]
See #67.

**Comment by HeahDude** [comment]
2.0.5 has been tagged.
