### ISSUE TITLE
FormType: Deprecation with Symfony 4.2 

### ISSUE THREAD

**Issue by althaus** [Exercise/HTMLPurifierBundle#63]
Hi,

starting with Symfony 4.2 all FormTypes need to implement the `getExtendedTypes` method:

https://symfony.com/blog/new-in-symfony-4-2-improved-form-type-extensions

> Not implementing the static getExtendedTypes() method in Exercise\HTMLPurifierBundle\Form\TypeExtension\HTMLPurifierTextTypeExtension when implementing the Symfony\Component\Form\FormTypeExtensionInterface is deprecated since Symfony 4.2. The method will be added to the interface in 5.0.

Cheers
Matthias

**Comment by althaus** [comment]
Darn... this is obviously content of the PR #61. As this is not merged keeping this issue open may help others.

**Comment by stof** [comment]
should be closed as the PR is merged now.
