### ISSUE TITLE
Scalar check instead is_string

### ISSUE THREAD

**Issue by markitosgv** [Exercise/HTMLPurifierBundle#64]
Why you're checking if data is scalar instead of string? Purify a boolean or integer value makes no sense, isn't it?

https://github.com/Exercise/HTMLPurifierBundle/blob/728672b6b0434f676aebfada4f3b85d5becb94de/Form/Listener/HTMLPurifierListener.php#L27

**Comment by HeahDude** [comment]
The form is not aware of the request format.
Any request handler implementation or custom call to `Form::submit` can pass something else than a string (think of a  `FileType` that may be submitted some `UploadedFile` instances from the request).

Only a compound/simple definition matters here, which is resolved by the type extension registering the listener when only extending `TextType` implementations which are not compound.

**Comment by HeahDude** [comment]
I'm closing here for the reason above. I propose to let the discussion continue in #65 instead.
Thanks!
