### ISSUE TITLE
Missing configuration for target attribute in documentation

### ISSUE THREAD

**Issue by lribi** [Exercise/HTMLPurifierBundle#78]
In the readme `a[target]` is whitelisted but HTML purifier needs additional configuration to actually allow the target attribute.

https://github.com/Exercise/HTMLPurifierBundle#whitelist-attributes
http://htmlpurifier.org/docs
http://htmlpurifier.org/live/configdoc/plain.html#Attr.AllowedFrameTargets

This could lead to some wrong configurations.

Maybe adding `Attr.AllowedFrameTargets` to the example could improve this?

**Comment by HeahDude** [comment]
Hello @lribi, thank you for opening this issue and sorry for the late answer.
I agree we could improve the example of the README, would you like to submit a PR?

**Comment by lribi** [comment]
Hi @HeahDude 

Sure, I'll make a PR when I find the time. Shouldn't take long.
