### ISSUE TITLE
Please can you help me explain what the cache is for?

### ISSUE THREAD

**Issue by matthew-gill** [Exercise/HTMLPurifierBundle#83]
Hello 👋 
Thanks for your support on this package, it's so helpful for us!

I have a quick question, if I may. 
I'd like to know more about the cache directory, and what is it used for?

We had a problem upgrading where we had two purifiers configured (loose and strict), originally we had two separate caches configured for each html profiles as that seemed the most sensible. After upgrading we got errors like this:
```
 User Warning: Base directory /Users/xxx/symfony/app/cache/loca_/htmlpurifier-loose does not exist,  
                      please create or change using %Cache.SerializerPath   
```

Once we removed the cache at a profile level and used the `default_cache_serializer_path` directive it worked.

Is it acceptable to use the same cache for multiple profiles (with different config) ?

And is the above a known issue?

Thanks in advance!

**Comment by HeahDude** [comment]
Closing for lack of feedback.
