### ISSUE TITLE
Add support for Symfony 6

### ISSUE THREAD

**Issue by Ishadijcks** [Exercise/HTMLPurifierBundle#85]
Could you update the `composer.json` to also support Symfony 6, which will be released by the end of this month (November)?

**Comment by bastien70** [comment]
Any news about the support of Symfony 6 ? I'm currently blocked by this vendor

```bash
- Root composer.json requires exercise/htmlpurifier-bundle ^3.1.0 -> satisfiable by exercise/htmlpurifier-bundle[v3.1.0].
    - exercise/htmlpurifier-bundle v3.1.0 requires symfony/config ~3.4 || ~4.0 || ^5.0 -> found symfony/config[v3.4.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev] but these were not loaded, likely because it conflicts with another require.
```

**Comment by sunchuo** [comment]
+1

**Comment by aramhovsepyan** [comment]
+1

**Comment by gyulaafodorr** [comment]
+1

**Comment by rtfjr86** [comment]
+1

**Comment by Cryde** [comment]
For people (like me) who search an alternative : https://github.com/tgalopin/html-sanitizer-bundle 
Also this kind of things will be available in SF6.1 https://symfony.com/blog/new-in-symfony-6-1-htmlsanitizer-component  
If you can't use yet SF6.1 this alternative is a good choice

**Comment by HeahDude** [comment]
v4.0 has just been tagged with support for Symfony 6. Thank you for your patience.
